import datetime as dt
import logging
import time
from typing import Optional

from openai import OpenAI
from trafilatura import extract, fetch_url
from trafilatura.metadata import extract_metadata
from trafilatura.sitemaps import sitemap_search

from app.core.db import SessionLocal
from app.core.db.models import ChatBotScrapedContent

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# Initialize OpenAI client
client = OpenAI()


def extract_urls_from_sitemap(sitemap_url: str) -> list[str]:
    """
    Extract all URLs from a sitemap XML file using trafilatura.

    Args:
        sitemap_url: The URL of the sitemap.xml file

    Returns:
        A list of URLs extracted from the sitemap
    """
    try:
        # Fetch the sitemap XML content first
        xml_content = fetch_url(sitemap_url)

        if not xml_content:
            logger.error(f"Failed to fetch sitemap from {sitemap_url}")
            return []

        # Use sitemap_search with the domain and XML content
        urls = list(sitemap_search(sitemap_url, xml_content))

        logger.info(f"Extracted {len(urls)} URLs from sitemap")
        return urls

    except Exception as e:
        logger.error(f"An error occurred while parsing sitemap: {e}")
        return []


def extract_content_from_url_and_save_to_db(url: str, max_retries: int = 3) -> bool:
    """
    Extract main content from a URL using trafilatura and save to database.
    If the URL already exists, updates the content. Embeddings will be regenerated
    by the create_vector_embeddings_of_scraped_content function.

    Args:
        url: The URL to extract content from
        max_retries: Maximum number of retry attempts for network failures (default: 3)

    Returns:
        True if successful, False otherwise
    """
    db = SessionLocal()

    # Retry logic for network operations
    for attempt in range(1, max_retries + 1):
        try:
            # Get HTML file to extract data from
            downloaded = fetch_url(url)

            if not downloaded:
                if attempt < max_retries:
                    logger.warning(
                        f"Failed to download: {url} (attempt {attempt}/{max_retries}), retrying..."
                    )
                    time.sleep(2**attempt)  # Exponential backoff: 2s, 4s, 8s
                    continue
                else:
                    logger.warning(
                        f"Failed to download: {url} after {max_retries} attempts"
                    )
                    return False

            # If download successful, break out of retry loop
            break

        except Exception as e:
            if attempt < max_retries:
                logger.warning(
                    f"Error downloading {url} (attempt {attempt}/{max_retries}): {e}, retrying..."
                )
                time.sleep(2**attempt)  # Exponential backoff
                continue
            else:
                logger.error(
                    f"Error downloading {url} after {max_retries} attempts: {e}"
                )
                db.close()
                return False

    try:

        # Extract metadata for title using trafilatura
        metadata = extract_metadata(downloaded)
        page_title = metadata.title if metadata else None

        # Extract main content as plain text
        content = extract(downloaded)

        if not content:
            logger.warning(f"No content extracted from: {url}")
            return False

        # Check if URL already exists in database
        existing_entry = (
            db.query(ChatBotScrapedContent)
            .filter(ChatBotScrapedContent.url == url)
            .first()
        )

        if existing_entry:
            # Update existing entry
            existing_entry.page_title = page_title
            existing_entry.content = content
            # Don't clear embeddings - they will be regenerated by the next step
            # but kept if regeneration fails
            existing_entry.updated_at = dt.datetime.now(dt.timezone.utc)
            db.commit()
            logger.info(f"Updated: {page_title or url}")
            return True
        else:
            # Create new entry
            scraped_content = ChatBotScrapedContent(
                url=url,
                page_title=page_title,
                content=content,
                created_at=dt.datetime.now(dt.timezone.utc),
                updated_at=dt.datetime.now(dt.timezone.utc),
            )
            db.add(scraped_content)
            db.commit()
            logger.info(f"Saved: {page_title or url}")
            return True

    except Exception as e:
        db.rollback()
        logger.error(f"Error processing {url}: {e}")
        return False
    finally:
        db.close()


def scrape_chatbot_website():
    """
    Main function to scrape the ChatBot website:
    1. Fetch sitemap
    2. Extract content from each URL and save to database
    """
    # Configuration
    sitemap_url = "https://chatbot.com/sitemap.xml"

    logger.info("Starting ChatBot Website Scraping...")

    # Extract URLs from sitemap
    logger.info(f"Step 1: Fetching sitemap from {sitemap_url}")
    urls = extract_urls_from_sitemap(sitemap_url)

    if not urls:
        logger.warning("No URLs found in sitemap")
        return

    logger.info(f"Found {len(urls)} URLs")

    # Process each URL and save to database
    logger.info("Extracting content and saving to database")

    # Filter the URLs before processing
    filtered_urls = []
    for url in urls:
        # Check 1: Only include chatbot.com domain
        if "chatbot.com" not in url:
            continue

        # Check 2: Exclude individual recipe pages (but keep /collection-recipes)
        if "/recipe/" in url:
            continue

        # Check 3: Exclude individual mixlist pages (but keep /mixlists)
        if "/mixlist/" in url:
            continue

        filtered_urls.append(url)

    logger.info(
        f"Filtered to {len(filtered_urls)} URLs (excluded {len(urls) - len(filtered_urls)} individual recipe/mixlist pages)"
    )

    for i, url in enumerate(filtered_urls, 1):
        logger.info(f"[{i}/{len(filtered_urls)}] Processing: {url}")
        extract_content_from_url_and_save_to_db(url)

        # Be respectful - add a small delay between requests
        time.sleep(1)

    logger.info("<<<=====Scraping Complete!=====>>>>")


def create_vector_embeddings_of_scraped_content():
    """
    Generate and store vector embeddings for all scraped content in the database.
    This function creates both content embeddings and URL embeddings in batches.
    """
    logger.info("<<<=======Starting Vector Embedding Generation...=====>>>")

    db = SessionLocal()
    try:
        # Fetch all scraped content entries that don't have embeddings
        logger.info("Fetching scraped content without embeddings...")
        content_entries = (
            db.query(ChatBotScrapedContent)
            .filter(
                (ChatBotScrapedContent.content_embedding.is_(None))
                | (ChatBotScrapedContent.url_embedding.is_(None))
            )
            .filter(ChatBotScrapedContent.content.isnot(None))
            .all()
        )

        if not content_entries:
            logger.info("All content entries already have embeddings!")
            return

        logger.info(f"Found {len(content_entries)} entries to process")

        # Process in batches
        batch_size = 100
        total_batches = (len(content_entries) + batch_size - 1) // batch_size

        for i in range(0, len(content_entries), batch_size):
            batch = content_entries[i : i + batch_size]
            batch_num = (i // batch_size) + 1

            logger.info(
                f"Processing batch {batch_num}/{total_batches} ({len(batch)} entries)..."
            )

            # Prepare texts for embedding
            content_texts = []
            url_texts = []
            for entry in batch:
                # Create a summary text combining title and content
                content_text = f"{entry.page_title or ''}\n{entry.content or ''}"
                # Truncate if too long (OpenAI has token limits)
                if len(content_text) > 8000:
                    content_text = content_text[:8000]
                content_texts.append(content_text)

                # Add URL text for URL embedding
                url_texts.append(entry.url)

            try:
                # Generate content embeddings using OpenAI with timeout
                logger.info(f"Generating content embeddings via OpenAI...")
                content_response = client.embeddings.create(
                    input=content_texts,
                    model="text-embedding-3-small",
                    dimensions=1536,
                    timeout=30.0,
                )

                # Generate URL embeddings using OpenAI with timeout
                logger.info(f"Generating URL embeddings via OpenAI...")
                url_response = client.embeddings.create(
                    input=url_texts,
                    model="text-embedding-3-small",
                    dimensions=1536,
                    timeout=30.0,
                )

                # Update database entries with embeddings only if generation succeeds
                # This preserves existing embeddings if API call fails
                logger.info(f"Saving embeddings to database...")
                for j, (content_data, url_data) in enumerate(
                    zip(content_response.data, url_response.data)
                ):
                    batch[j].content_embedding = content_data.embedding
                    batch[j].url_embedding = url_data.embedding
                    batch[j].updated_at = dt.datetime.now(dt.timezone.utc)

                db.commit()
                logger.info(f"Successfully processed batch {batch_num}/{total_batches}")

            except Exception as e:
                db.rollback()
                logger.error(f"Error processing batch {batch_num}: {e}")
                continue

            # Small delay between batches to avoid rate limits
            if i + batch_size < len(content_entries):
                time.sleep(1)

        logger.info(
            f"Successfully generated embeddings for {len(content_entries)} entries"
        )

    except Exception as e:
        logger.error(f"Error during embedding generation: {e}")
        db.rollback()
    finally:
        db.close()


if __name__ == "__main__":
    # Step 1: Scrape the website
    scrape_chatbot_website()

    # Step 2: Generate embeddings for scraped content
    create_vector_embeddings_of_scraped_content()
